= ml-project-template

A template for ML projects striking a balance between reproducibility and rapid iteration.

== Requirements and versions:

* Python 3.5
* Git
* Tensorflow 1.5

*Important:* When commiting, remember to be *in* the virtual environment, for hooks to work.

Note: Collab still runs on different versions of everything, but this should be a good approximation (2018/02/27).

== Setup

Make sure there is no `venv/` directory in your repo. If there is, remove it.
Run the following commands:
```
./setup/create_venv.sh
source venv/bin/activate
./setup/setup_venv.sh
```

*Important:* For all commands here, we assume you are source into the virtual environment: `source venv/bin/activate`

== Starting the notebook server

Run: `jupyter notebook .` in the project root directory.

=== Tensorboard

To run Tensorboard in the notebook server, go to the specified log directory, and select New > Tensorboard. A pop-up window will open (make sure to enable those in your browser).

Hint: Only do this once, in the `data_out/` folder.

If you are on Colab, add the following cell to your notebook, ideally in a "section":

```
COLAB = True
import os

if COLAB:
    import resources.colab_utils.tboard as tboard

    %cd /content
    ROOT_DIR = '/content'
    REPO_DIR = os.path.join(ROOT_DIR, 'ml_project_template')
    LOG_DIR = os.path.join(REPO_DIR, 'data_out')

    if not os.path.isdir(REPO_DIR):
      !git clone https://github.com/oskopek/ml_project_template.git
    if not os.path.isdir(LOG_DIR):
      os.makedirs(LOG_DIR)
    %cd 'ml_project_template'
    %ls

    # will install `ngrok`, if necessary
    # will create `log_dir` if path does not exist
    tboard.launch_tensorboard(bin_dir=ROOT, log_dir=LOG_DIR)
else:
    %pwd
```

A URL will be in the output, use that to connect to Tensorboard in your browser. The URL should only work from your machine (localhost).

== Formatting

Unfortunately, there is no sane way to autoformat notebooks. Please do that manually, in the notebook, using the code_prettify
extensions (press Ctrl+Shift+L). All other Python files will get autoformatted by YAPF.

== Directory structure

* `data_in/` -- input data and associated scripts/configs
* `data_out/` -- output data and logs + associated scripts/configs
* `docker/` -- setup and configs for running stuff inside and outside of Docker
* `features/` -- feature preprocessing and normalization Python code + configs
* `flags/` -- command line flags, model parameters, etc.
* `models/` -- scripts defining the models + hyperparameters
* `notebooks/` -- data exploration and other rapid development notebooks
** Models from here should eventually be promoted into `models/`
* `resources/` -- Python utilities
* `setup/` -- environemnt setup and verification scripts in Python/Bash
* `venv/` -- the (local) Python virtual environemnt

== Running

Try it out:
```
docker run IMG bash # opens a shell
docker run IMG jupyter # runs Jupyter
docker run IMG notebook notebooks/test.ipynb # Runs the notebook
docker run IMG models/mnist_gan_graph.py flags/gan.json # Runs the mnist gan graph model with flags from the specified file
```
