FROM tensorflow/tensorflow:1.5.0-gpu-py3

LABEL maintainer="Ondrej Skopek <oskopek@oskopek.com>"

# Set up our notebook config.
COPY docker/jupyter_notebook_config.py /root/.jupyter/

# Copy the repo.
COPY / /ml

# Update and create data_out
RUN apt-get update && mkdir /ml/data_out

# TensorBoard
EXPOSE 6006
# IPython
EXPOSE 8888

WORKDIR "/ml"

ENTRYPOINT ["./docker/run.sh"]
CMD []
