FROM tensorflow/tensorflow:1.5.0-py3

LABEL maintainer="Ondrej Skopek <oskopek@oskopek.com>"

# Set up our notebook config.
COPY docker/jupyter_notebook_config.py /root/.jupyter/

# Copy the repo.
COPY / /ml
WORKDIR "/ml"

# Update and create data_out
RUN apt-get update && mkdir data_out && ./setup/create_venv.sh

# TensorBoard
EXPOSE 6006
# IPython
EXPOSE 8888

ENTRYPOINT ["./docker/run.sh"]
CMD []
